[tool.bumpversion]
current_version = "0.9"
commit = true
tag = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)(.(?P<patch>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}",
    "{major}.{minor}"
]

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "data/metainfo/org.endlessos.Key.metainfo.xml.in.in"
# This crude regex will break if the release tag contains any "/" or ">" characters.
regex = true
search = "<release\\s[^>]*\\s?version=\"{current_version}\\+next\"[^/>]*"
replace = "<release version=\"{new_version}\" date=\"{now:%Y-%m-%d}\" type=\"stable\""
